title: Saddleback Autonomous Vehicle
description: Saddleback Team for Sparkfun AVC 2016

url: 
baseurl: "http://saddlebackcss.github.io/AutonomousCar"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: SaddlebackCSS/AutonomousCar
   twitter: 
   facebook: 
   email: 

google_analytics: 
