#!/bin/bash

# Script for compiling overlay files and placing them in the correct directory.
# Eventually this script will loop through all files in /overlay, compile
# them and place them in appropriately named directories... eventually
echo "Compiling the overlay from .dts to .dtbo"

# Compile overlay for P9_16 - Steering
dtc -O dtb -o /lib/firmware/car_pwm_controls-00A0.dtbo -b 0 -@ car_pwm_controls-00A0.dts
